# Generated by Django 5.0.1 on 2025-01-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='active',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='whatsappmessage',
            name='status',
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='current_state',
            field=models.CharField(default='initial', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='temp_data',
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_bot.location')),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('amenities', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_bot.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_phone', models.CharField(max_length=20)),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whatsapp_bot.roomtype')),
            ],
        ),
    ]
