# Generated by Django 5.0.1 on 2025-01-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_bot', '0002_location_remove_whatsappcontact_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='current_state',
        ),
        migrations.RemoveField(
            model_name='whatsappcontact',
            name='temp_data',
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whatsappcontact',
            name='last_message_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
